export let MobExperiences = {
    "minecraft:armadillo": [1, 3],
    "minecraft:axolotl": [1, 3],
    "minecraft:bee": [1, 3],
    "minecraft:blaze": 10,
    "minecraft:bogged": [6, 8],
    "minecraft:breeze": 10,
    "minecraft:camel": [1, 3],
    "minecraft:cat": [1, 3],
    "minecraft:cave_spider": 5,
    "minecraft:chicken": [1, 3],
    "minecraft:cow": [1, 3],
    "minecraft:creeper": 5,
    "minecraft:dolphin": [1, 3],
    "minecraft:donkey": [1, 3],
    "minecraft:drowned": [13, 15],
    "minecraft:elder_guardian": 10,
    "minecraft:enderman": 5,
    "minecraft:endermite": 3,
    "minecraft:evocation_illager": 10,
    "minecraft:cod": [1, 3],
    "minecraft:fox": [1, 3],
    "minecraft:frog": [1, 3],
    "minecraft:ghast": [6, 8],
    "minecraft:glow_squid": [1, 3],
    "minecraft:goat": [1, 3],
    "minecraft:guardian": 10,
    "minecraft:happy_ghast": [1, 3],
    "minecraft:hoglin": 5,
    "minecraft:horse": [1, 3],
    "minecraft:husk": [13, 15],
    "minecraft:llama": [1, 3],
    "minecraft:magma_cube": 5,
    "minecraft:mooshroom": [1, 3],
    "minecraft:mule": [1, 3],
    "minecraft:ocelot": [1, 3],
    "minecraft:panda": [1, 3],
    "minecraft:parrot": [1, 3],
    "minecraft:phantom": 5,
    "minecraft:pig": [1, 3],
    "minecraft:piglin": [2, 3],
    "minecraft:piglin_brute": 20,
    "minecraft:pillager": [6, 8],
    "minecraft:player": [0, 100],
    "minecraft:polar_bear": [1, 3],
    "minecraft:pufferfish": [1, 3],
    "minecraft:rabbit": [1, 3],
    "minecraft:ravager": 20,
    "minecraft:salmon": [1, 3],
    "minecraft:sheep": [1, 3],
    "minecraft:shulker": 5,
    "minecraft:silverfish": 5,
    "minecraft:skeleton": [6, 8],
    "minecraft:skeleton_horse": [1, 3],
    "minecraft:slime": 5,
    "minecraft:sniffer": [1, 3],
    "minecraft:spider": 5,
    "minecraft:squid": [1, 3],
    "minecraft:stray": [6, 8],
    "minecraft:strider": [1, 3],
    "minecraft:trader_llama": [1, 3],
    "minecraft:tropicalfish": [1, 3],
    "minecraft:turtle": [1, 3],
    "minecraft:vex": [6, 8],
    "minecraft:vindicator": [6, 8],
    "minecraft:warden": 5,
    "minecraft:witch": [6, 8],
    "minecraft:wither": 50,
    "minecraft:wither_skeleton": [6, 8],
    "minecraft:wolf": [1, 3],
    "minecraft:zoglin": 5,
    "minecraft:zombie": [13, 15],
    "minecraft:zombie_horse": [1, 3],
    "minecraft:zombie_pigman": [13, 15],
    "minecraft:zombie_villager": [13, 15],
    "minecraft:zombie_villager_v2": [13, 15]
};
